### ISSUE TITLE
OR needed on drawChar

### ISSUE THREAD

**Issue by Bwooce** [freetronics/DMD2#1]
I have a use case that's surely not unique. I have a fixed width numeric font (FIXEDNUMS7x15_H). All good. I can fit 4 digits onto one DMD with 3 columns to spare.

I really want to use those columns for the colon (:) which are only 2 wide, but being a fixed width font it doesn't work. I can position things correctly but its not currently possible to overlap characters with the DMD2 library - it blanks out the full fixed width.

It was with DMD1 using GRAPHICS_OR option e.g.
```
dmd.drawChar(npos,  -1, ':', GRAPHICS_OR);
```

I could re-engineer my font to be variable width, but it occurs to me that being able to print characters over other pre-drawn things is a useful feature.

Could I suggest dropping the reverse option and reinstating the options?
```
//Pixel/graphics writing modes (bGraphicsMode)
#define GRAPHICS_NORMAL    0
#define GRAPHICS_INVERSE   1
#define GRAPHICS_TOGGLE    2
#define GRAPHICS_OR        3
#define GRAPHICS_NOR       4
```

**Comment by projectgus** [comment]
Hi again Bwooce,

It's been more than six months, so you've probably moved on from this a bit. However I've merged your changes in bdb5b8f854 - if you get a chance to try it then please let me know how you find it.

I'm going to close this issue for now, but feel free to reopen if there are still shortcomings.

Angus
