### ISSUE TITLE
Please add the panel connections to arduino

### ISSUE THREAD

**Issue by rtek1000** [freetronics/DMD2#10]
Congratulations!
The DMD and DMD2 is a good job!

Please add to description: 

http://i351.photobucket.com/albums/q452/plclark3/MatrixCable.jpg

Thank you!

**Comment by alexzzzzz** [comment]
The panel is connected on your circuit. With a library of DMD Russian letters are displayed well, but with a library DMD2 displayed only Latin characters. I assume that the library DMD2 not correctly calculated the size of the character with 0x80 - 0xFF

**Comment by h4rm0n1c** [comment]
Dead URL, closing issue.

However your point appears to be around documentation and has been noted.
