### ISSUE TITLE
Intel Galileo Gen2 Using Library DMD2 

### ISSUE THREAD

**Issue by aakamal88** [freetronics/DMD2#11]
Hi Master,

Can use DMD2 library in Intel Galileo Gen 2?
Pls Advise...

**Comment by projectgus** [comment]
Hi,

Sorry for the slow reply. We don't officially support the Intel Galileo, the main thing is that timer support is different on a different board like this.

It may still work if you use SoftDMD mode (without timers) and manually call the `dmd.scanDisplay();` method frequently - best if you can set up a timer (using whatever support Galileo has for timers) on there.

Sorry I can't be more help. You may have more luck asking on a Galileo support forum, where people will be more familiar with the technology.
