### ISSUE TITLE
Latest tagged release does not include ESP8266 pin swap.

### ISSUE THREAD

**Issue by gkoh** [freetronics/DMD2#16]
Hello there,

Thanks for a fantastic library.
The latest tagged release (0.0.3) does not yet include the pinout swap for the ESP8266.
I discovered this when using platformio to build a test and used the reference comment for the pinout and wiring (and things didn't quite work).

It would be nice if a new release could be tagged so platformio libraries might be updated.

**Comment by h4rm0n1c** [comment]
0.0.4 will be released soon with this oversight corrected.
