### ISSUE TITLE
DMD2 With Long Text

### ISSUE THREAD

**Issue by Avong** [freetronics/DMD2#17]
I have downloaded DMD2, it worked fine with max of 4(32x16) modules. 
but i got truncated text if i tried scrolling long message up to 92 character.
had anyone have this experience? please any advice. 
Also, the scrolling is not smooth.

**Comment by helmisusanto** [comment]
me tooo, i have problem scrolling long text  with DMD2. i have try to define max of with panel is 7. but it not working, i try to implement DMD model but many function is not same with DMD2. please someone help us!!!

**Comment by jhonoryza** [comment]
use box.print(String);
