### ISSUE TITLE
more than 7 screens, esp8266 will restart

### ISSUE THREAD

**Issue by baoshuai9527** [freetronics/DMD2#19]
I use dmd2 library can define up to only 7 screens, if more than 7 screens, esp8266 will restart， Have anyone run into this problem?

**Comment by h4rm0n1c** [comment]
It is likely the ESP8266 is running out of time to perform other tasks that it must perform to keep the esp's watchdog timer or the wireless hardware from spitting the dummy and causing a reset.

**Comment by CTWF** [comment]
Any improvement to support more than 7 screen now?
