### ISSUE TITLE
NodeMCU 1.0 frequent reset 

### ISSUE THREAD

**Issue by kV43** [freetronics/DMD2#21]
Even with example code also the NodeMCU is resetting after approx 11-12 seconds with the following message.

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v40106aac
~ld
⸮
please suggest

**Comment by jhonoryza** [comment]
dont use delay function
