### ISSUE TITLE
support for esp32

### ISSUE THREAD

**Issue by jhonoryza** [freetronics/DMD2#25]
is there a support for esp32 board?

**Comment by szymoni** [comment]
i'm also looking forward to use this library with esp32. Any chances soon?

**Comment by h4rm0n1c** [comment]
Not at this stage.

ESP32 was too new when I originally started writing the ESP8266 support, the arduino environment for it was still very early in development and I could not afford the time, money or energy to start on a new platform at the time.

Barring a pull request from someone else, this isn't likely to happen soon. It's definitely something I'd like to see supported myself though as I have plans to use the DMD with an esp32 at some point.

**Comment by learn2007** [comment]
hi
is there a support for esp32 board now?

**Comment by sayanlp99** [comment]
esp32 support arrived yet?
