### ISSUE TITLE
Error in DMD2_Text.cpp in DMDFrame::charWidth method

### ISSUE THREAD

**Issue by jrossouw** [freetronics/DMD2#4]
After reading the char width from the font header, there is a line of code to check if the returned width for a space char is zero (line 219):

if(width == 0 && c == ' ') ...

This does not work, as the value of c have already been adjusted by the offset of the 1st char in the font. This method currently always returns 0 for a space in a variable width font. The code needs to read:

if(width == 0 && letter == ' ') ...

**Comment by projectgus** [comment]
Hi jrossouw,

Thanks for reporting this bug, sorry it's taken us so long to get back to you.

I just pushed a commit, 44c4325c8b, that replaces the charWidth() implementation with a much simpler one from FTOLED. I think that mitigates this problem, but please let me know if it doesn't.

Thanks again for the report, sorry again for neglecting you over the holidays!


Angus
