### ISSUE TITLE
Font Cyrillic

### ISSUE THREAD

**Issue by alexzzzzz** [freetronics/DMD2#9]
Support for Russian fonts. DMD but supports a number of disadvantages. Is it possible to make the support of Cyrillic in the library DMD2?

**Comment by alexzzzzz** [comment]
The panel is connected on your circuit. With a library of DMD Russian letters are displayed well, but with a library DMD2 displayed only Latin characters. I assume that the library DMD2 not correctly calculated the size of the character with 0x80 - 0xFF

**Comment by h4rm0n1c** [comment]
This library is beta, as far as I know, there is no support for alternative character sets at this stage.
My own level of expertise as maintainer leaves me high and dry in terms of being able to implement this myself, but if I receive a pull request implementing such functionality I will definitely review, test and merge if possible.
